# pre_order listbydate 列出 preorder 清单
@hostname = https://mlg3.wulidev.com
@role = agent
@action = pre_order
POST {{hostname}}/api/{{role}}/{{action}}.php
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3JpZCI6IjAiLCJ0YWJsZSI6ImFnZW50Iiwic3lzdXNlciI6ImNrc3VubnkiLCJleHAiOjE2NzQ1NTIyMzR9.XARfpGY_AWCpgDzcm2MZSfw3BJrS52QqMODb7KamAgE

{
    "action":"listbydate",
    "begin":"2022-11-22",
    "end": "2022-12-29",
    "status":"cancelled"
}

###
# pre_order listbyid 列出 preorder 清单
POST {{hostname}}/api/{{role}}/{{action}}.php
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3JpZCI6MSwidGFibGUiOiJhZ2VudCIsImRibmFtzdXNlciI6ImNrc3VubnkiLCJleHAiOjE2NzAxNjc0NDR9.qgV3EivCz7i5KFmrpq_PDiueYMeW1gk7Zr06EIjFNwQ

{
    "action":"listbyid",
    "id":32
}
###
# pre_order new  清单
POST {{hostname}}/api/{{role}}/{{action}}.php
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3JpZCI6IjAiLCJ0YWJsZSI6ImFnZW50Iiwic3lzdXNlciI6ImNrc3VubnkiLCJleHAiOjE2NzQ1NTIyMzR9.XARfpGY_AWCpgDzcm2MZSfw3BJrS52QqMODb7KamAgE

{
    "action":"new",
    "mbid":"354719",
    "order_mbid":null,
    "data":{}
}
###
# pre_order new  清单
POST {{hostname}}/api/{{role}}/{{action}}.php
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3JpZCI6IjAiLCJ0YWJsZSI6ImFnZW50Iiwic3lzdXNlciI6ImNrc3VubnkiLCJleHAiOjE2NzQ1NTIyMzR9.XARfpGY_AWCpgDzcm2MZSfw3BJrS52QqMODb7KamAgE

{
    "action":"getPreOrderNamebyPhone",
    "phone":7742518836
}

###
# pre_order edit  修改預收訂單
POST {{hostname}}/api/{{role}}/{{action}}.php
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3JpZCI6IjAiLCJ0YWJsZSI6ImFnZW50Iiwic3lzdXNlciI6ImNrc3VubnkiLCJleHAiOjE2NzQyNzk3NzN9.6Zq-u5spXo1qd4oFVbEazWGwKv8KZ_PWVBBR1kf0RKE

{
    "action": "edit",
    "preorderid": "230",
    "data": {
        "paydetail": "test test test test"
    }
}


###
# pre_order edit  刪除預收訂單檔案
POST {{hostname}}/api/{{role}}/{{action}}.php
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3JpZCI6MSwidGFibGUiOiJhZ2VudCIsImRibmFtZSI6bnVsbCwic3lzdXNlciI6ImNrc3VubnkiLCJleHAiOjE2NzIwMTg1NDl9.tSkjLD95X7vSWtXv3lzB7yTt8Fc5Lb0IbRtApAEw4mA

{
    "action": "del_up_files",
    "filename": [
        "58_16707881780_coupon-svgrepo-com.png"
    ]
}